#!/bin/bash

# Captures a screenshot from a user defined area, and stores it in the screenshots folder.

TIME=$(date +"%Y-%m-%d %H.%M.%S")
FILENAME="$HOME/Dropbox/Screenshots/Screenshot $TIME.png"
maim -s "$FILENAME"

# Open the file in the file manager
nemo "$FILENAME"
